name: Build and test

on:
  workflow_dispatch:


jobs:

  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2

    - name: Download tar file
      run: |
        wget https://github.com/msalemor/cai/blob/main/release/cai-0.0.1.zip

    - name: Extract tar file
      run: |
        unzip -xzf cai-0.0.1.zip

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.24.0'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
