name: Build and test

on:
  workflow_dispatch:


jobs:

  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2

    - name: Download and extract zip file
      run: |
        wget https://github.com/msalemor/cai/raw/refs/heads/main/release/cai-0.1.0.zip
        unzip cai-0.1.0.zip
        rm cai-0.1.0.zip
        
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.24.0'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
