name: Build and test

on:
  workflow_dispatch:


jobs:

  build:
    name: Test
    runs-on: ubuntu-latest
    env:
      CAI_ENDPOINT: ${{ secrets.CAI_ENDPOINT }}
      CAI_KEY: ${{ secrets.CAI_KEY }}
      CAI_MODEL: gpt-4o
      CAI_TYPE: azure
    steps:
    - uses: actions/checkout@v4.2.2

    - name: Download and extract zip file
      run: |
        mkdir cai
        cd cai
        wget https://github.com/msalemor/cai/raw/refs/heads/main/release/cai-0.1.0.zip
        unzip cai-0.1.0.zip
        rm cai-0.1.0.zip
        ./cai eval -s .. -j ../junit.xml
        
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.24.0'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
