name: Manual build and test skipping

on:
  workflow_dispatch:

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    env:
      CAI_ENDPOINT: ${{ secrets.CAI_ENDPOINT }}
      CAI_KEY: ${{ secrets.CAI_KEY }}
      CAI_MODEL: gpt-4o
      CAI_TYPE: azure
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Download and extract zip file
        run: |
          mkdir cai
          cd cai
          wget https://github.com/msalemor/cai/releases/download/v0.1.0/cai-linux-amd64-v0.1.1.zip
          unzip cai-linux-amd64-v0.1.1.zip
          rm cai-linux-amd64-v0.1.1.zip
          ./cai eval -s .. -j ../junit.xml -k .py

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.24.0"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
