name: Publish Release

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      
      - name: Build executable
        run: go build -o cai
      
      - name: Create release archive
        run: |
          mkdir -p release
          cp cai release/
          cp evaluations.json release/
          cd release
          zip -r ../cai-linux-amd64-${{ github.ref_name }}.zip .
      
      # - name: Create Release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref_name }}
      #     release_name: Release ${{ github.ref_name }}
      #     draft: false
      #     prerelease: false
      #   id: create_release      

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            cai-linux-amd64-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
